memo/urls.py
from django.urls import path
from rest_framework.routers import DefaultRouter
from .views import (
    CardsAPIView,
    DecksAPIView,
    CardAnswersAPIView,
    PresetDecksAPIView,
    AddPresetDeckToUserDeckAPIView,
    MyLearningTableAPIView,
    ConsecutiveDaysAPIView,
)
from memo.views import DecksAPIView

router = DefaultRouter()
router.register("decks", DecksAPIView, basename="decks")
urlpatterns = router.urls

app_name = "memo"

urlpatterns = [
    path("cards/<int:pk>/", CardsAPIView.as_view(), name="card"),
    path("cards/", CardsAPIView.as_view(), name="cards"),
    path(
        "cards/<int:pk>/card-answer/", CardAnswersAPIView.as_view(), name="card_answers"
    ),
    path("card-answer/", CardAnswersAPIView.as_view(), name="answer_card"),
    path("preset-decks/", PresetDecksAPIView.as_view(), name="preset_decks"),
    path(
        "preset-decks/<int:pk>/add-to-decks/",
        AddPresetDeckToUserDeckAPIView.as_view(),
        name="preset_deck_to_deck",
    ),
    path(
        "my-learning-results/",
        MyLearningTableAPIView.as_view(),
        name="my_learning_result",
    ),
    path(
        "consecutive-days/",
        ConsecutiveDaysAPIView.as_view(),
        name="consecutive-days",
    ),
]

memo_front/urls.py
from django.urls import path
from .views import deck, assigment

app_name = "memo_front"

urlpatterns = [
    path("deck/<slug:deck_id>/", deck, name="deck"),
    path("assigment/<slug:deck_id>/", assigment, name="assigment"),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from memo_front.views import (
    redirect_if_not_logged,
    register_request,
    presets,
    my_learning,
)
from memo.urls import router

urlpatterns = [
    path("", redirect_if_not_logged, name="index"),
    path("presets/", presets, name="presets"),
    path("my-learning/", my_learning, name="my_learning"),
    path("accounts/", include("django.contrib.auth.urls")),
    path("acounts/register/", register_request, name="register"),
    path("admin/", admin.site.urls),
    path("cards/", include("memo_front.urls"), name="cards"),
    path("api/", include("memo.urls"), name="memo"),
    path("api/", include(router.urls)),
]

templates/frontend/cards/assigment.html
{% extends 'frontend/base.html' %} 
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="progress" style="width:100%">
                <div class="progress-bar bg-success" role="progressbar" id="barSuccess"></div>
                <div class="progress-bar bg-danger" role="progressbar" id="barFailure"></div>
              </div>
        </div>
    </div>
    <div class="jumbotron">
        <div class="row align-items-center" style="padding-bottom:30px;">
            <div class="col-md-12">
                <h1 id="title"></h1>
                <div id="legend"></div>
            </div>
          </div>
          <div class="container">
            <div class="row" id="deck">
            </div>
          </div>
      </div>
    </div>
</div>
{% endblock content %} 
{% block js %}
    <script>
    let deckData = [];
    let cardIndex = 0;
    let resultData = [];

    let progressTotal = 0;
    let progressFailure = 0;
    let progressSuccess = 0;
    
    $(document).ready(function () {
        $.ajax({
            url: "/api/decks/{{ deck_id }}/",
            type: "GET",
            beforeSend: function(request) {
                request.setRequestHeader("Authorization", "Token " + authToken);
            },
            dataType: "json",
            success: function (data) {
                loadPageTemplate(data);
            },
            error: function(){
                alert("Deck not found!");
                window.location.href = "/";
            },
            complete: function(){
                mainPageLoad();
            }
        });
    });

    const answerSubmit = (card_id) => {
        let answerText = $("#answerText").val();

        if(answerText == ""){
            return alert("Fill the textarea");
        }
        
        if($("#cardAnswer").text().trim().toUpperCase() == answerText.trim().toUpperCase()){
            progressSuccess++;
            sendAnswerHistory(true,card_id,answerText);
        }else{
            progressFailure++;
            sendAnswerHistory(false,card_id,answerText);
        }

        progressBar();
        toggleCard();

        if((progressSuccess + progressFailure) == progressTotal){
            changeToFinishButton();
            return;
        }

        changeToNextCardButton();
    }

    const shuffleArray = (list) => {
        return list.sort(() => Math.random() - 0.5);
    }

    const progressBar = () => {
        $("#barSuccess").css("width", (100 * progressSuccess) / progressTotal + "%");
        $("#barFailure").css("width", (100 * progressFailure) / progressTotal + "%");
    }
    
    const loadPageTemplate = (data) => {
        deckData = shuffleArray(data.cards);
        progressTotal = deckData.length;
        title.innerHTML = `<a href="{% url 'memo_front:deck' deck_id=deck_id  %}">
            <div class="goBack" id="goBack">&#8249;</div></a> ` + data.name;
        legend.innerHTML = data.description;
        deck.innerHTML = loadCardAndAnswerBoxTemplate(data.cards[cardIndex]);
    }

    function goToNextCard(nextCardId){
        cardIndex++;
        deck.innerHTML = loadCardAndAnswerBoxTemplate(deckData[cardIndex])
    }

    function loadCardAndAnswerBoxTemplate(data) {
        return `<div class="col-md-6">
                    <div class="flip">
                        <div class="card"> 
                          <div class="face front"> 
                            <div class="inner">   
                                <h1 id="cardQuestion">${data.front}</h1>
                            </div>
                          </div> 
                          <div class="face back"> 
                            <div class="inner"> 
                              <h1 id="cardAnswer">${data.back}</h1>
                            </div>
                          </div>
                        </div>	 
                    </div>
                </div>
                <div class="col-md-6 align-self-center" style="text-align: center;">
                    <div class="form-group">
                    <label for="answerText">Write the correct answer in text area below</label>
                    <textarea class="form-control" id="answerText" rows="3"></textarea>
                    </div>
                    <div class="form-group" id="buttonDiv">
                    <button id="answer" class="btn btn-primary" onclick="answerSubmit(${data.id})">Answer</button>
                    </div>
                </div>`;
    }

    const changeToNextCardButton = (nextCardId) => {
        buttonDiv.innerHTML = `<button id="answerButton" class="btn btn-warning" onclick="goToNextCard(${nextCardId})">Next Card</button>`;
    }

    const changeToFinishButton = () => {
        buttonDiv.innerHTML = `<button id="finishButton" class="btn btn-success" onclick="showResult()">Finish</button>`;
    }

    const showResult = () => {
        let resultTemplate = ``;
        resultTemplate += `
        <div>
            <p><b>Total of cards:</b> ${progressTotal}</p>
            <p><b>Correct:</b> ${(100 * progressSuccess) / progressTotal + "%"}</p>
            <p><b>Incorrect:</b> ${(100 * progressFailure) / progressTotal + "%"}</p>
        </div>
        <table class="table table-hover">
        <thead>
          <tr class="table-dark">
            <th scope="col">Front</th>
            <th scope="col">Back</th>
            <th scope="col">Your Answer</th>
            <th scope="col">Result</th>
          </tr>
        </thead>
        <tbody>`;

        resultData.map((card) => { resultTemplate += `
            <tr>
              <td>${card.front}</td>
              <td>${card.back}</td>
              <td>${card.user_answer}</td>
              <td>${returnIcon(card.correct)}</td>
            </tr>
        `});

        resultTemplate += `
            </tbody>
        </table>`;

        deck.innerHTML = resultTemplate;
    }

    const toggleCard = () => {
        $(".card").toggleClass("flipped");
    }

    const sendAnswerHistory = (correct,card_id,answer) => {
        let jsonData = {
            "correct":correct,
            "card":card_id,
            "user_answer":answer,
            "front": cardQuestion.innerHTML,
            "back": cardAnswer.innerHTML
        };

        resultData.push(jsonData);

        $.ajax({
            url: "/api/card-answer/",
            type: "POST",
            beforeSend: function(request) {
                request.setRequestHeader("Authorization", "Token " + authToken);
            },
            data: JSON.stringify(jsonData),
            contentType: "application/json; charset=utf-8",
            dataType: "json",
            error: function(){
                alert('Card answer was not sent')
            }
        });
    }

</script>
{% endblock js %}

templates/frontend/cards/index.html
{% extends 'frontend/base.html' %} 
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div style="width:100%; height: 1rem;"></div>
        </div>
    </div>
    <div class="jumbotron">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-md-6">
                    <h1 id="title"></h1>
                    <div id="legend"></div>
                </div>
                <div class="col-md-6 align-self-center" style="text-align: center;">
                    <div id="buttons"></div>
                </div>
            </div>
        </div>
            <div class="container">
                <div class="row" id="cards">
                </div>
          </div>
      </div>
    </div>
</div>
{% endblock content %} 
{% block js %}
<script>
    $(document).ready(function () {
        $.ajax({
            url: "/api/decks/{{ deck_id }}/",
            type: "GET",
            beforeSend: function(request) {
                request.setRequestHeader("Authorization", "Token " + authToken);
            },
            dataType: "json",
            success: function (data) {
                if(data == ""){
                    alert('Deck not found!');
                    window.location.href = "/";
                }else{
                    loadPageTemplate(data);
                    disableStartButtonIfCardDoesntExist();
                }
            },
            complete: function(){
                mainPageLoad();
            }
        });
    });

    function loadPageTemplate(data){
        title.innerHTML = `<a href="{% url 'index' %}">
            <div class="goBack" id="goBack">&#8249;</div></a> ` + data.name;
        legend.innerHTML = '<p><b>Created at:</b> ' + data.created_at + '<p>' + data.description + '</p>';
        buttons.innerHTML = `<div style="padding-bottom:10px;">
            <a href="{% url 'memo_front:assigment' deck_id=deck_id  %}"><button type="button" class="btn btn-success btn-lg" style="margin-right:10px" id="startButton">Start</button></a>
            <button type="button" class="btn btn-info btn-lg" onClick="openModal('addCard',${data.id})">Add card</button>
            <button type="button" class="btn btn-danger btn-lg" onclick="openModal('deleteDeck',${data.id})">Delete this deck</button>
        </div>`;

        for (let index = 0; index < data.cards.length; index++){
          $("#cards").append(loadCardTemplate(data.cards[index]));
        }
    }
    
    const loadCardTemplate = (data) => {
      let answerHistoryButtonDisabled =  (data.card_history.length > 0) ? '' : 'disabled';

      card = ` 
        <div class="col-md-4" id="card_id_${data.id}">
            <div class="card text-center any-card" style="width: 18rem; margin-bottom:10px; height:250px; cursor: pointer;">
                <div class="card-header text-muted"></div>
                <div class="card-body">
                    <h2 class="card-title cardFrontSelector">${data.front}</h2>
                    <input type="hidden" class="cardBackSelector" value="${data.back}">
                    <p class="card-text">Created at: ${data.created_at}</p>
                </div>
            <div class="card-footer text-muted">
                <button type="button" class="btn btn-outline-danger btn-sm" 
                onClick="deleteCard(${data.id})">Delete</button>
                <button type="button" class="btn btn-outline-warning btn-sm" 
                onclick="openModal('updateCard',${data.id})">Update</button>
                <button type="button" class="btn btn-outline-info btn-sm" 
                onclick="openModal('historyCard',${data.id})" ${answerHistoryButtonDisabled}>History</button>
            </div>
        </div>`;
        return card;
    }    
    
    function getAnswerHistory(card_id){
        $.ajax({
            url: "/api/cards/" + card_id + "/card-answer/",
            type: "GET",
            beforeSend: function(request) {
                request.setRequestHeader("Authorization", "Token " + authToken);
            },
            dataType: "json",
            success: function (data) {
                let result = "";

                data.map((answer) => { result += `
                <tr>
                <td>${answer.user_answer}</td>
                <td>${returnIcon(answer.correct)}</td>
                <td>${answer.created_at}</td>
                </tr>`});

              $("#table_answer").append(result);
            },
        })
    }

    const getCardSelectorValue = (id) => {
        let text = {};
        text.front = $('#card_id_' + id + ' .cardFrontSelector').text();
        text.back = $('#card_id_' + id + ' .cardBackSelector').val();

        return text;
    }

    const disableStartButtonIfCardDoesntExist = () => {
        ($("#cards").children().length > 0) ?  
        $('#startButton').prop("disabled", false) : 
        $('#startButton').prop("disabled", true);
    }

    const updateCard = (card_id) => {
        isModalLoading(true);
        cardFront = $("#cardFront").val();
        cardBack = $("#cardBack").val();

        if(cardFront == "" || cardBack.length == ""){
            alert('Please fill out the required field(s)')
            return;
        }
        
        let jsonData = {
            "front": cardFront,
            "back": cardBack
        };

        $.ajax({
            url: "/api/cards/" + card_id + "/",
            type: "PUT",
            beforeSend: function(request) {
                request.setRequestHeader("Authorization", "Token " + authToken);
            },
            data: JSON.stringify(jsonData),
            contentType: "application/json; charset=utf-8",
            dataType: "json",
            success: function (response) {
                $('#modal').modal('hide');
                $('#card_id_' + card_id + ' .cardFrontSelector').text(cardFront)
                $('#card_id_' + card_id + ' .cardBackSelector').val(cardBack)

            },
            error: function(){
                alert('Unable to update. Try again.');
            },
            complete: function(){
                isModalLoading(false);
            }
        });
        
    }

    const addCard = (deck_id) => {
        isModalLoading(true);
        cardFront = $("#cardFront").val();
        cardBack = $("#cardBack").val();

        if(cardFront == "" || cardBack.length == ""){
            alert('Please fill out the required field(s)')
            return;
        }

        let jsonData = {
            "front": cardFront,
            "back": cardBack,
            "deck": deck_id
        };

        $.ajax({
            url: "/api/cards/",
            type: "POST",
            beforeSend: function(request) {
                request.setRequestHeader("Authorization", "Token " + authToken);
            },
            data: JSON.stringify(jsonData),
            contentType: "application/json; charset=utf-8",
            dataType: "json",
            success: function (response) {
                $('#modal').modal('hide');
                $("#cards").append(loadCardTemplate(response));
                disableStartButtonIfCardDoesntExist();
            },
            error: function(){
                alert("Unable to add a card");
            },
            complete: function(){
                isModalLoading(false);
            }
        });
    }

    const deleteCard = (card_id) => {  
        isModalLoading(true);
        $.ajax({
            url: "/api/cards/" + card_id + "/",
            type: "DELETE",
            beforeSend: function(request) {
                request.setRequestHeader("Authorization", "Token " + authToken);
            },
            dataType: "json",
            success: function (response) {
                document.getElementById("card_id_" + card_id).remove();
                disableStartButtonIfCardDoesntExist();
            },
            error: function(response){
                alert("Unable to delete the card. Try again.");
            },
            complete: function(){
                isModalLoading(false);
            }
        });
    }

    const deleteDeck = (deck_id) => {  
        isModalLoading(true);
        $.ajax({
            url: "/api/decks/" + deck_id + "/",
            type: "DELETE",
            beforeSend: function(request) {
                request.setRequestHeader("Authorization", "Token " + authToken);
            },
            dataType: "json",
            success: function (response) {
                window.location.href = "/";
            },
            error: function (response){
                alert('Unable to delete the deck. Try again.');
            },
            complete: function(){
                isModalLoading(false);
            }
        });
    }

</script>
{% endblock %}